apiVersion: v1
kind: Service
metadata:
  name: legacyweb-weather
  namespace: {{ .Values.nsWeather }}
  labels:
    app: legacyweb-weather
spec:
  type: NodePort
  selector:
    app: legacyweb-weather
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.internalPort }}
      targetPort: {{ .Values.internalPort }}
      nodePort: {{ .Values.externalPort }}
