apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacymail
  namespace: {{ .Values.nsEmail }}
  labels:
    app: legacymail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacymail
  template:
    metadata:
      labels:
        app: legacymail
    spec:
      containers:
        - name: legacymail
          image: 'jusschwa/legacymail:latest'
          env:
{{- if .Values.popHostName }}
            - name: POP3_DST_HOST
              value: '{{ .Values.popHostName }}'
            - name: POP3_DST_PORT
              value: '{{ .Values.popDstPort }}'
{{- end }}
{{- if .Values.imapDstHost }}
            - name: IMAP_DST_HOST
              value: '{{ .Values.imapDstHost }}'
            - name: IMAP_DST_PORT
              value: '{{ .Values.imapDstPort }}'
{{- end }}
{{- if .Values.smtpDstHost }}
            - name: SMTP_DST_HOST
              value: '{{ .Values.smtpDstHost }}'
            - name: SMTP_DST_PORT
              value: '{{ .Values.smtpDstPort }}'
{{- end }}
          ports:
{{- if .Values.popInternalPort }}
            - containerPort: {{ .Values.popInternalPort }}
{{- end }}
{{- if .Values.imapInternalPort }}
            - containerPort: {{ .Values.imapInternalPort }}
{{- end }}
{{- if .Values.smtpInternalPort }}
            - containerPort: {{ .Values.smtpInternalPort }}
{{- end }}
{{- if .Values.legacyAuth }}
        - name: legacymail-postfix
          image: 'jusschwa/legacymail-postfix:latest'
          env:
            - name: SMTP_DST_HOST
              value: '{{ .Values.smtpLegacyDstHost }}'
            - name: SMTP_DST_PORT
              value: '{{ .Values.smtpLegacyDstPort }}'
          envFrom:
            - secretRef:
                name: legacymail-credentials
          ports:
            - containerPort: {{ .Values.smtpLegacyInternalPort }}
{{- end }}
