apiVersion: v1
data:
  EMAIL_USERNAME: {{ .Values.emailUser | b64enc }}
  EMAIL_PASSWORD: {{ .Values.emailPassword | b64enc }}
kind: Secret
metadata:
  name: legacymail-credentials
  namespace: {{ .Values.nsEmail }}
type: Opaque
