apiVersion: v1
kind: Service
metadata:
  name: legacymail
  namespace: {{ .Values.nsEmail }}
  labels:
    app: legacymail
spec:
  type: NodePort
  selector:
    app: legacymail
  ports:
{{- if .Values.popDstPort }}
    - name: pop
      protocol: TCP
      port: {{ .Values.popDstPort }}
      targetPort: {{ .Values.popInternalPort }}
      nodePort: {{ .Values.popExternalPort }}
{{- end }}
{{- if .Values.imapDstPort }}
    - name: imap
      protocol: TCP
      port: {{ .Values.imapDstPort }}
      targetPort: {{ .Values.imapInternalPort }}
      nodePort: {{ .Values.imapExternalPort }}
{{- end }}
{{- if .Values.smtpDstPort }}
    - name: smtp
      protocol: TCP
      port: {{ .Values.smtpDstPort }}
      targetPort: {{ .Values.smtpInternalPort }}
      nodePort: {{ .Values.smtpExternalPort }}
{{- end }}